"""Public portable knowledge contracts and helpers for OmniVia Core."""

# ruff: noqa: RUF022
# RUF022 would resort __all__. This barrel is a 1:1 port of
# `omnivia_memory.knowledge.__all__` and
# tests/canonical_migration/test_knowledge_barrel.py gates it on exact ordered
# parity with that legacy list, matching how test_parity.py gates other Slice A
# leaves on normalized AST parity. Comments are the only thing that gate cannot
# see, so the suppression is the fix; resorting __all__ has to land in the
# legacy source first.

from omnivia_core._shared.validation import ValidationResult
from omnivia_core.knowledge.models import (
    BUILTIN_GRAPH_NODE_KINDS,
    BUILTIN_GRAPH_RELATIONS,
    BUILTIN_OBJECT_KINDS,
    EXTENSION_MANIFEST_CONTRACT_VERSION,
    GRAPH_CONTRACT_VERSION,
    KNOWLEDGE_CONTRACT_VERSION,
    AgentGraphContext,
    ContractVersion,
    GraphConfidence,
    GraphEdge,
    GraphEvidenceStrength,
    GraphFragment,
    GraphNode,
    GraphOrigin,
    GraphReviewStatus,
    GraphSensitivity,
    GraphSourceType,
    GraphVisibility,
    KnowledgeClaim,
    KnowledgeCollection,
    KnowledgeExtensionManifest,
    KnowledgeLink,
    KnowledgeObject,
    KnowledgeSource,
    KnowledgeSpace,
    SourceRef,
)
from omnivia_core.knowledge.normalize import (
    normalize_graph_edge_id,
    normalize_graph_node_id,
    normalize_graph_node_kind,
    normalize_graph_relation,
    normalize_identifier,
    normalize_label,
    normalize_object_id,
    normalize_object_kind,
    normalize_source_path,
    normalize_space_id,
    normalize_tags,
)
from omnivia_core.knowledge.validation import (
    check_contract_version_compatibility,
    summarize_confidence,
    summarize_review_status,
    summarize_sensitivity,
    validate_agent_graph_context,
    validate_graph_edge,
    validate_graph_fragment,
    validate_graph_node,
    validate_knowledge_claim,
    validate_knowledge_collection,
    validate_knowledge_extension_manifest,
    validate_knowledge_link,
    validate_knowledge_object,
    validate_knowledge_source,
    validate_knowledge_space,
    validate_source_ref,
)

__all__ = [
    "AgentGraphContext",
    "BUILTIN_GRAPH_NODE_KINDS",
    "BUILTIN_GRAPH_RELATIONS",
    "BUILTIN_OBJECT_KINDS",
    "ContractVersion",
    "EXTENSION_MANIFEST_CONTRACT_VERSION",
    "GRAPH_CONTRACT_VERSION",
    "GraphConfidence",
    "GraphEdge",
    "GraphEvidenceStrength",
    "GraphFragment",
    "GraphNode",
    "GraphOrigin",
    "GraphReviewStatus",
    "GraphSensitivity",
    "GraphSourceType",
    "GraphVisibility",
    "KNOWLEDGE_CONTRACT_VERSION",
    "KnowledgeClaim",
    "KnowledgeCollection",
    "KnowledgeExtensionManifest",
    "KnowledgeLink",
    "KnowledgeObject",
    "KnowledgeSource",
    "KnowledgeSpace",
    "SourceRef",
    "ValidationResult",
    "check_contract_version_compatibility",
    "normalize_graph_edge_id",
    "normalize_graph_node_id",
    "normalize_graph_node_kind",
    "normalize_graph_relation",
    "normalize_identifier",
    "normalize_label",
    "normalize_object_id",
    "normalize_object_kind",
    "normalize_source_path",
    "normalize_space_id",
    "normalize_tags",
    "summarize_confidence",
    "summarize_review_status",
    "summarize_sensitivity",
    "validate_agent_graph_context",
    "validate_graph_edge",
    "validate_graph_fragment",
    "validate_graph_node",
    "validate_knowledge_claim",
    "validate_knowledge_collection",
    "validate_knowledge_extension_manifest",
    "validate_knowledge_link",
    "validate_knowledge_object",
    "validate_knowledge_source",
    "validate_knowledge_space",
    "validate_source_ref",
]
