"""Phase 1 Semantic Registry domain layer (standard library only).

Immutable, validated models for semantic models/versions/elements, the 18
typed change-operation kinds (spec section 11), deterministic ordering and
diff classification, consumer/dependency/binding records, and canonical
digesting. No persistence, no LLM calls, no third-party dependencies: this is
the pure domain layer used by the runtime's SQLite repository and manual
authoring service (spec 9.1, Phase 1 deliverables).
"""

from __future__ import annotations

from omnivia_core.semantic_registry.canonical import (
    CANONICALIZER_VERSION,
    canonical_bytes,
    change_set_digest,
    change_set_payload,
    content_digest,
    model_version_digest,
    model_version_payload,
    operation_payload,
)
from omnivia_core.semantic_registry.consumers import (
    Consumer,
    ConsumerDependency,
    ConsumerKind,
    DependencyMode,
    ExactBinding,
)
from omnivia_core.semantic_registry.diff import (
    VersionImpact,
    classify_change_set,
    classify_operation,
    impact_to_compatibility,
)
from omnivia_core.semantic_registry.errors import (
    SemanticConflictError,
    SemanticErrorCode,
    SemanticRegistryError,
    SemanticValidationError,
)
from omnivia_core.semantic_registry.ids import (
    DEFAULT_ALLOCATOR,
    IdAllocator,
    UUIDv7Allocator,
    uuid7,
)
from omnivia_core.semantic_registry.models import (
    ActionType,
    Alias,
    Concept,
    Constraint,
    ConstraintKind,
    LifecycleState,
    ModelVersion,
    Property,
    PropertyValueKind,
    Relationship,
    SemanticElement,
    SemanticModel,
    VocabularyMember,
)
from omnivia_core.semantic_registry.operations import (
    ChangeOperation,
    OperationKind,
    add_action_type,
    add_alias,
    add_concept,
    add_constraint,
    add_property,
    add_relationship,
    add_vocabulary_member,
    change_action_contract,
    change_cardinality,
    change_description,
    change_disjointness,
    change_domain_range,
    change_equivalence,
    change_hierarchy,
    change_label,
    deprecate_element,
    remove_element,
    replace_element,
)
from omnivia_core.semantic_registry.ordering import order_operations
from omnivia_core.semantic_registry.records import (
    ActivationRecord,
    ChangeRecord,
    CompatibilityClassification,
    ConsumerImpactFinding,
    DecisionExplanation,
    HistoryEntry,
    PublicationRecord,
    ReviewDecision,
    ReviewRecord,
    Severity,
    ValidationFinding,
)

__all__ = [
    "CANONICALIZER_VERSION",
    "DEFAULT_ALLOCATOR",
    "ActionType",
    "ActivationRecord",
    "Alias",
    "ChangeOperation",
    "ChangeRecord",
    "CompatibilityClassification",
    "Concept",
    "Constraint",
    "ConstraintKind",
    "Consumer",
    "ConsumerDependency",
    "ConsumerImpactFinding",
    "ConsumerKind",
    "DecisionExplanation",
    "DependencyMode",
    "ExactBinding",
    "HistoryEntry",
    "IdAllocator",
    "LifecycleState",
    "ModelVersion",
    "OperationKind",
    "Property",
    "PropertyValueKind",
    "PublicationRecord",
    "Relationship",
    "ReviewDecision",
    "ReviewRecord",
    "SemanticConflictError",
    "SemanticElement",
    "SemanticErrorCode",
    "SemanticModel",
    "SemanticRegistryError",
    "SemanticValidationError",
    "Severity",
    "UUIDv7Allocator",
    "ValidationFinding",
    "VersionImpact",
    "VocabularyMember",
    "add_action_type",
    "add_alias",
    "add_concept",
    "add_constraint",
    "add_property",
    "add_relationship",
    "add_vocabulary_member",
    "canonical_bytes",
    "change_action_contract",
    "change_cardinality",
    "change_description",
    "change_disjointness",
    "change_domain_range",
    "change_equivalence",
    "change_hierarchy",
    "change_label",
    "change_set_digest",
    "change_set_payload",
    "classify_change_set",
    "classify_operation",
    "content_digest",
    "deprecate_element",
    "impact_to_compatibility",
    "model_version_digest",
    "model_version_payload",
    "operation_payload",
    "order_operations",
    "remove_element",
    "replace_element",
    "uuid7",
]
