"""Runtime Execution Planes: a non-authoritative, package-neutral execution seam.

Five modules, one seam. :mod:`profile` holds the frozen profile, executor and
session-provider descriptors plus the shared vocabulary, :mod:`planes` the
execution-class behaviours, :mod:`registry` the static source-qualified
registry that decides which executor or session provider build is routable,
:mod:`workflow` a provisional in-memory EP2 conformance oracle for
workflow materialisation, routing and one run's replay-equivalent
observations, and :mod:`loop` the bounded loop runner and iteration-ledger
oracle for the complete `LoopPlan`.

The two loop names are two different questions and are not one ontology:
:class:`~omnivia_core_runtime.execution.workflow.LoopDefinition` with its
:class:`~omnivia_core_runtime.execution.workflow.LoopController` bounds a loop's
*spend*, while :class:`~omnivia_core_runtime.execution.loop.FrozenLoopPlan` with
its :class:`~omnivia_core_runtime.execution.loop.LoopRunner` bounds and records a
loop's *iterations*. Neither restates the other's vocabulary.

The reference vocabularies are closed and their members are spelled in exact
uppercase -- ``AGENT``, ``APPROVED``, ``COMMAND``, ``TERMINAL`` and the rest.
An execution class and an executor kind are separate vocabularies and are never
equated: the first says what a profile runs, the second what a build is.

Nothing in this package imports storage, the scheduler, recovery, a transport
or Platform, and nothing writes canonical state. Every decision it makes is a
value returned or a refusal raised.
"""

from omnivia_core_runtime.execution.loop import (
    CANCEL_REMAINING,
    COMPLETE_ALL,
    DISPOSITION_CANCELLED_IN_FLIGHT,
    DRAIN_IN_FLIGHT,
    FAIL_LOOP,
    ITERATION_CANCELLED,
    ITERATION_OUTCOMES,
    ITERATION_SKIPPED,
    LOOP_CANCELLATION_POLICIES,
    LOOP_MODE_PARALLEL,
    LOOP_MODE_SEQUENTIAL,
    LOOP_MODES,
    LOOP_ORDER_GUARANTEES,
    LOOP_PARTIAL_SUCCESS_POLICIES,
    LOOP_RUNNING,
    LOOP_SETTLED,
    LOOP_STATES,
    LOOP_STOPPING,
    LOOP_ZIP_MISMATCH_POLICIES,
    ORDER_ITERATION_IDENTITY,
    ORDER_SETTLEMENT,
    RECORD_AND_CONTINUE,
    RECORD_AND_STOP_AFTER_CURRENT,
    ZIP_PAD_WITH_ABSENT,
    ZIP_REFUSE,
    ZIP_TRUNCATE_TO_SHORTEST,
    FrozenLoopPlan,
    IterationLaunch,
    IterationLedgerEntry,
    LateResult,
    LoopElement,
    LoopRunner,
    replay_ledger,
)
from omnivia_core_runtime.execution.planes import (
    LEASE_EXPIRED,
    LEASE_HELD,
    LEASE_RELEASED,
    LEASE_STATES,
    REQUIRED_DISPATCH_TRUST,
    SESSION_ACTIVE,
    SESSION_ORPHANED,
    SESSION_RELEASED,
    SESSION_STATES,
    SESSION_UNKNOWN,
    STATUS_CANCELLED,
    STATUS_COMPLETED,
    CapabilityProposal,
    ComponentOutcome,
    ComponentPlane,
    ComponentRequest,
    ComponentResult,
    DispatchIntent,
    GovernedDispatchPlane,
    ReconcileResult,
    SessionEvent,
    SessionLease,
    SessionSnapshot,
    StatefulSessionPlane,
)
from omnivia_core_runtime.execution.profile import (
    BUILD_TRUST_APPROVED,
    BUILD_TRUST_DISABLED,
    BUILD_TRUST_PROTOTYPE,
    BUILD_TRUST_QUARANTINED,
    BUILD_TRUST_STATES,
    CONTRACT_VERSION,
    EXECUTION_CLASS_AGENT,
    EXECUTION_CLASS_DETERMINISTIC,
    EXECUTION_CLASS_EFFECT,
    EXECUTION_CLASS_WAIT,
    EXECUTION_CLASSES,
    EXECUTOR_KIND_BROWSER,
    EXECUTOR_KIND_COMMAND,
    EXECUTOR_KIND_FILESYSTEM,
    EXECUTOR_KIND_GIT,
    EXECUTOR_KIND_INTEGRATION,
    EXECUTOR_KIND_OTHER,
    EXECUTOR_KINDS,
    HEALTH_QUARANTINED,
    HEALTH_READY,
    HEALTH_STATES,
    ISOLATION_MAX,
    ISOLATION_MIN,
    PROFILE_TRUST_APPROVED,
    PROFILE_TRUST_DISABLED,
    PROFILE_TRUST_DRAFT,
    PROFILE_TRUST_QUARANTINED,
    PROFILE_TRUST_STATES,
    ROUTABLE_HEALTH,
    SESSION_KIND_ACP,
    SESSION_KIND_BROWSER,
    SESSION_KIND_OTHER,
    SESSION_KIND_REMOTE_EXECUTION,
    SESSION_KIND_TERMINAL,
    SESSION_KINDS,
    ExecutionContractError,
    ExecutionError,
    ExecutionLineage,
    ExecutionRefused,
    ExecutorDescriptor,
    RuntimeProfileDescriptor,
    SessionProviderDescriptor,
    canonical_hash,
    derive_id,
)
from omnivia_core_runtime.execution.registry import (
    ENTRY_EXECUTOR,
    ENTRY_SESSION_PROVIDER,
    EntryKey,
    RegistryEntry,
    RegistryEvent,
    RuntimeExecutionRegistry,
)
from omnivia_core_runtime.execution.workflow import (
    BRANCH_BLOCKED,
    BRANCH_MATCHED,
    BRANCH_OPERATOR_EQUALS,
    BRANCH_OPERATOR_NOT_EQUALS,
    BRANCH_OPERATOR_PRESENT,
    BRANCH_OPERATORS,
    BRANCH_OUTCOMES,
    BRANCH_UNMATCHED,
    CANCELLATION_COOPERATIVE,
    CANCELLATION_NONE,
    CANCELLATION_POSTURES,
    IMPLEMENTATION_POSTURE_PROPOSES_EFFECT,
    IMPLEMENTATION_POSTURE_PURE,
    IMPLEMENTATION_POSTURES,
    OUTCOME_FAILED,
    OUTCOME_SUCCEEDED,
    OUTCOMES,
    ROUTE_AGENT,
    ROUTE_CHILD_WORKFLOW,
    ROUTE_DETERMINISTIC,
    ROUTE_EFFECT,
    ROUTE_WAIT,
    ROUTES,
    BranchDefinition,
    BranchObservation,
    BranchResult,
    ChildCorrelation,
    ChildWorkflowCorrelator,
    ChildWorkflowDefinition,
    CompletionEvaluator,
    CompletionRule,
    DeterministicImplementationDescriptor,
    DeterministicImplementationRegistry,
    ImplementationHistoryEvent,
    LoopController,
    LoopDefinition,
    MaterialisedStep,
    MaterialisedWorkflow,
    PlanObservation,
    RouteDecision,
    RunOracle,
    StepDefinition,
    StepRouter,
    WorkflowDefinition,
    materialise_workflow,
)

__all__ = [
    "BRANCH_BLOCKED",
    "BRANCH_MATCHED",
    "BRANCH_OPERATORS",
    "BRANCH_OPERATOR_EQUALS",
    "BRANCH_OPERATOR_NOT_EQUALS",
    "BRANCH_OPERATOR_PRESENT",
    "BRANCH_OUTCOMES",
    "BRANCH_UNMATCHED",
    "BUILD_TRUST_APPROVED",
    "BUILD_TRUST_DISABLED",
    "BUILD_TRUST_PROTOTYPE",
    "BUILD_TRUST_QUARANTINED",
    "BUILD_TRUST_STATES",
    "CANCELLATION_COOPERATIVE",
    "CANCELLATION_NONE",
    "CANCELLATION_POSTURES",
    "CANCEL_REMAINING",
    "COMPLETE_ALL",
    "CONTRACT_VERSION",
    "DISPOSITION_CANCELLED_IN_FLIGHT",
    "DRAIN_IN_FLIGHT",
    "ENTRY_EXECUTOR",
    "ENTRY_SESSION_PROVIDER",
    "EXECUTION_CLASSES",
    "EXECUTION_CLASS_AGENT",
    "EXECUTION_CLASS_DETERMINISTIC",
    "EXECUTION_CLASS_EFFECT",
    "EXECUTION_CLASS_WAIT",
    "EXECUTOR_KINDS",
    "EXECUTOR_KIND_BROWSER",
    "EXECUTOR_KIND_COMMAND",
    "EXECUTOR_KIND_FILESYSTEM",
    "EXECUTOR_KIND_GIT",
    "EXECUTOR_KIND_INTEGRATION",
    "EXECUTOR_KIND_OTHER",
    "FAIL_LOOP",
    "HEALTH_QUARANTINED",
    "HEALTH_READY",
    "HEALTH_STATES",
    "IMPLEMENTATION_POSTURES",
    "IMPLEMENTATION_POSTURE_PROPOSES_EFFECT",
    "IMPLEMENTATION_POSTURE_PURE",
    "ISOLATION_MAX",
    "ISOLATION_MIN",
    "ITERATION_CANCELLED",
    "ITERATION_OUTCOMES",
    "ITERATION_SKIPPED",
    "LEASE_EXPIRED",
    "LEASE_HELD",
    "LEASE_RELEASED",
    "LEASE_STATES",
    "LOOP_CANCELLATION_POLICIES",
    "LOOP_MODES",
    "LOOP_MODE_PARALLEL",
    "LOOP_MODE_SEQUENTIAL",
    "LOOP_ORDER_GUARANTEES",
    "LOOP_PARTIAL_SUCCESS_POLICIES",
    "LOOP_RUNNING",
    "LOOP_SETTLED",
    "LOOP_STATES",
    "LOOP_STOPPING",
    "LOOP_ZIP_MISMATCH_POLICIES",
    "ORDER_ITERATION_IDENTITY",
    "ORDER_SETTLEMENT",
    "OUTCOMES",
    "OUTCOME_FAILED",
    "OUTCOME_SUCCEEDED",
    "PROFILE_TRUST_APPROVED",
    "PROFILE_TRUST_DISABLED",
    "PROFILE_TRUST_DRAFT",
    "PROFILE_TRUST_QUARANTINED",
    "PROFILE_TRUST_STATES",
    "RECORD_AND_CONTINUE",
    "RECORD_AND_STOP_AFTER_CURRENT",
    "REQUIRED_DISPATCH_TRUST",
    "ROUTABLE_HEALTH",
    "ROUTES",
    "ROUTE_AGENT",
    "ROUTE_CHILD_WORKFLOW",
    "ROUTE_DETERMINISTIC",
    "ROUTE_EFFECT",
    "ROUTE_WAIT",
    "SESSION_ACTIVE",
    "SESSION_KINDS",
    "SESSION_KIND_ACP",
    "SESSION_KIND_BROWSER",
    "SESSION_KIND_OTHER",
    "SESSION_KIND_REMOTE_EXECUTION",
    "SESSION_KIND_TERMINAL",
    "SESSION_ORPHANED",
    "SESSION_RELEASED",
    "SESSION_STATES",
    "SESSION_UNKNOWN",
    "STATUS_CANCELLED",
    "STATUS_COMPLETED",
    "ZIP_PAD_WITH_ABSENT",
    "ZIP_REFUSE",
    "ZIP_TRUNCATE_TO_SHORTEST",
    "BranchDefinition",
    "BranchObservation",
    "BranchResult",
    "CapabilityProposal",
    "ChildCorrelation",
    "ChildWorkflowCorrelator",
    "ChildWorkflowDefinition",
    "CompletionEvaluator",
    "CompletionRule",
    "ComponentOutcome",
    "ComponentPlane",
    "ComponentRequest",
    "ComponentResult",
    "DeterministicImplementationDescriptor",
    "DeterministicImplementationRegistry",
    "DispatchIntent",
    "EntryKey",
    "ExecutionContractError",
    "ExecutionError",
    "ExecutionLineage",
    "ExecutionRefused",
    "ExecutorDescriptor",
    "FrozenLoopPlan",
    "GovernedDispatchPlane",
    "ImplementationHistoryEvent",
    "IterationLaunch",
    "IterationLedgerEntry",
    "LateResult",
    "LoopController",
    "LoopDefinition",
    "LoopElement",
    "LoopRunner",
    "MaterialisedStep",
    "MaterialisedWorkflow",
    "PlanObservation",
    "ReconcileResult",
    "RegistryEntry",
    "RegistryEvent",
    "RouteDecision",
    "RunOracle",
    "RuntimeExecutionRegistry",
    "RuntimeProfileDescriptor",
    "SessionEvent",
    "SessionLease",
    "SessionProviderDescriptor",
    "SessionSnapshot",
    "StatefulSessionPlane",
    "StepDefinition",
    "StepRouter",
    "WorkflowDefinition",
    "canonical_hash",
    "derive_id",
    "materialise_workflow",
    "replay_ledger",
]
