"""Deprecated compatibility root for the canonical ``omnivia_core`` package.

``omnivia-memory`` is a compatibility facade. Every name this root publishes is
imported, unmodified, from its approved canonical owner or barrel -- the frozen
root import table names eleven ``omnivia_core`` modules, and several of those are
barrels that re-export a name rather than the module that defines it. There is no
local definition, alias, wildcard, wrapper, or dynamic attribute hook here, so
``omnivia_memory.X is <the approved module it is imported from>.X`` holds for
every name below, and because that module re-exports rather than redefines, the
object is also the one its defining module binds.

The 182 advertised portable contracts and ``__version__`` come from
``omnivia_core``. Four bindings stay out of ``__all__`` and remain importable
for callers that ask for them explicitly: ``MemoryCreate`` and ``MemoryUpdate``
are the canonical Core inputs, while ``Database`` and ``MemoryService`` are
deliberately still owned by the legacy runtime modules imported below --
``omnivia_memory.persistence`` and ``omnivia_memory.memory.service`` -- which
Core does not own and does not package.

New code should import from ``omnivia_core`` directly; see this distribution's
README for the migration guidance. Importing this package emits no warning, by
design (ADR-036): nothing here writes to stdout, stderr, or a logger.
"""

from omnivia_core import __version__
from omnivia_core._shared.validation import ValidationResult
from omnivia_core.app_manifest import (
    AppManifest,
    AppManifestValidationError,
    AppState,
    DataSource,
    validate_app_manifest,
)
from omnivia_core.component_contract import (
    AgentAction,
    AgentBackedComponentContract,
    AgentBehavior,
    AgentRunRecord,
    AgentRunStatus,
    ApprovalPolicy,
    AuditRequirement,
    ComponentAIMode,
    ComponentConnectorScope,
    ComponentContract,
    ComponentContractValidationError,
    ComponentDataSource,
    ComponentFamily,
    ComponentGraphScope,
    ComponentInput,
    ComponentOutput,
    ComponentOutputType,
    ComponentPermission,
    ComponentRunMode,
    ComponentSafetyLevel,
    PermissionPolicy,
    ProvenanceBehavior,
    ProvenanceRequirement,
    validate_agent_run_record,
    validate_component_contract,
)
from omnivia_core.control_plane import (
    CONTROL_PLANE_CONTRACT_VERSION,
    CONTROL_PLANE_SCHEMA_VERSION,
    DANGEROUS_SIDE_EFFECTS,
    Agent,
    Approval,
    AuditEvent,
    Automation,
    Capability,
    CapabilityType,
    CatalogueArtifactVerification,
    Connection,
    ConnectionKind,
    ConsultantAccessGrant,
    ConsultantGrantStatus,
    ControlPlaneManifest,
    ControlPlaneRunStatus,
    ControlPlaneValidationError,
    ExecutionMode,
    ExecutionResult,
    ImportedCandidateSet,
    ImportRecord,
    ImportSourceChange,
    ImportSourceProtocol,
    ImportSpecValidation,
    LifecycleState,
    LocalApprovalNotification,
    LocalApprovalNotificationChannel,
    LocalApprovalNotificationEvent,
    LocalApprovalNotificationStatus,
    LocalModelInvocationRecord,
    LocalObservabilityLogRecord,
    LocalUsageLedgerEntry,
    Policy,
    PolicyAttributeCondition,
    PolicyAttributeExpression,
    PolicyDecision,
    PolicyDecisionReason,
    PolicyDecisionRecord,
    PolicyRulePack,
    PolicyTemplate,
    RunMode,
    RunObservabilityMetrics,
    RunRecord,
    RunStepRecord,
    RunStepStatus,
    RunStepType,
    SecretMetadata,
    SecretReference,
    SecretResolutionResult,
    SecretStorageScope,
    SideEffect,
    SyncConflictStrategy,
    SyncDirection,
    SyncRule,
    TenantIsolationRule,
    Trigger,
    TriggerEventEnvelope,
    TriggerIngestionResult,
    TriggerKind,
    WorkspaceRef,
    compile_policy_expression,
    detect_import_source_change,
    import_asyncapi_candidates,
    import_catalogue_candidates,
    import_catalogue_generated_candidates,
    import_mcp_candidates,
    import_openapi_candidates,
    manifest_from_dict,
    validate_asyncapi_import_spec,
    validate_control_plane_manifest,
    validate_mcp_import_spec,
    validate_openapi_import_spec,
    verify_catalogue_artifacts,
)
from omnivia_core.knowledge import (
    BUILTIN_GRAPH_NODE_KINDS,
    BUILTIN_GRAPH_RELATIONS,
    BUILTIN_OBJECT_KINDS,
    EXTENSION_MANIFEST_CONTRACT_VERSION,
    GRAPH_CONTRACT_VERSION,
    KNOWLEDGE_CONTRACT_VERSION,
    AgentGraphContext,
    ContractVersion,
    GraphConfidence,
    GraphEdge,
    GraphEvidenceStrength,
    GraphFragment,
    GraphNode,
    GraphOrigin,
    GraphReviewStatus,
    GraphSensitivity,
    GraphSourceType,
    GraphVisibility,
    KnowledgeClaim,
    KnowledgeCollection,
    KnowledgeExtensionManifest,
    KnowledgeLink,
    KnowledgeObject,
    KnowledgeSource,
    KnowledgeSpace,
    SourceRef,
    check_contract_version_compatibility,
    normalize_graph_edge_id,
    normalize_graph_node_id,
    normalize_graph_node_kind,
    normalize_graph_relation,
    normalize_identifier,
    normalize_label,
    normalize_object_id,
    normalize_object_kind,
    normalize_source_path,
    normalize_space_id,
    normalize_tags,
    summarize_confidence,
    summarize_review_status,
    summarize_sensitivity,
    validate_agent_graph_context,
    validate_graph_edge,
    validate_graph_fragment,
    validate_graph_node,
    validate_knowledge_claim,
    validate_knowledge_collection,
    validate_knowledge_extension_manifest,
    validate_knowledge_link,
    validate_knowledge_object,
    validate_knowledge_source,
    validate_knowledge_space,
    validate_source_ref,
)
from omnivia_core.memory.models import MemoryCreate, MemoryUpdate  # noqa: F401
from omnivia_core.memory_graph import (
    EvidenceGraphResponse,
    GraphPreviewResponse,
    MemoryGraphFixture,
    RetrievalTrace,
    build_memory_graph_fixture,
)
from omnivia_core.module_manifest import (
    Entrypoint,
    Integrity,
    ModuleKind,
    ModuleManifest,
    ModuleManifestValidationError,
    Permission,
    PublishedTarget,
    validate_module_manifest,
)
from omnivia_core.provenance import Source, SourceType
from omnivia_core.run_ledger import (
    RUN_LEDGER_CONTRACT_VERSION,
    RUN_LEDGER_PATH_ENV,
    TERMINAL_RUN_STATUSES,
    EvidenceFileRef,
    RunLedgerEntry,
    RunLedgerProvenance,
    RunLedgerStatus,
    validate_evidence_file_ref,
    validate_run_ledger_entry,
    validate_run_ledger_provenance,
)

from omnivia_memory.memory.service import MemoryService  # noqa: F401
from omnivia_memory.persistence import Database  # noqa: F401

# The frozen root export contract pins this exact order, so RUF022's sorted-
# __all__ preference is suppressed here rather than the order being changed.
__all__ = [  # noqa: RUF022
    "AgentGraphContext",
    "AppManifest",
    "AppManifestValidationError",
    "AppState",
    "AgentAction",
    "AgentBackedComponentContract",
    "AgentBehavior",
    "AgentRunRecord",
    "AgentRunStatus",
    "ApprovalPolicy",
    "AuditRequirement",
    "BUILTIN_GRAPH_NODE_KINDS",
    "BUILTIN_GRAPH_RELATIONS",
    "BUILTIN_OBJECT_KINDS",
    "ComponentAIMode",
    "ComponentConnectorScope",
    "ComponentContract",
    "ComponentContractValidationError",
    "ComponentDataSource",
    "ComponentFamily",
    "ComponentGraphScope",
    "ComponentInput",
    "ComponentOutput",
    "ComponentOutputType",
    "ComponentPermission",
    "ComponentRunMode",
    "ComponentSafetyLevel",
    "ContractVersion",
    "CONTROL_PLANE_CONTRACT_VERSION",
    "CONTROL_PLANE_SCHEMA_VERSION",
    "DANGEROUS_SIDE_EFFECTS",
    "DataSource",
    "Entrypoint",
    "EXTENSION_MANIFEST_CONTRACT_VERSION",
    "EvidenceFileRef",
    "EvidenceGraphResponse",
    "GRAPH_CONTRACT_VERSION",
    "GraphConfidence",
    "GraphPreviewResponse",
    "GraphEdge",
    "GraphEvidenceStrength",
    "GraphFragment",
    "GraphNode",
    "GraphOrigin",
    "GraphReviewStatus",
    "GraphSensitivity",
    "GraphSourceType",
    "GraphVisibility",
    "Integrity",
    "CatalogueArtifactVerification",
    "ImportSpecValidation",
    "ImportedCandidateSet",
    "KNOWLEDGE_CONTRACT_VERSION",
    "KnowledgeClaim",
    "KnowledgeCollection",
    "KnowledgeExtensionManifest",
    "KnowledgeLink",
    "KnowledgeObject",
    "KnowledgeSource",
    "KnowledgeSpace",
    "MemoryGraphFixture",
    "ModuleKind",
    "ModuleManifest",
    "ModuleManifestValidationError",
    "Permission",
    "PermissionPolicy",
    "PublishedTarget",
    "ProvenanceBehavior",
    "ProvenanceRequirement",
    "RUN_LEDGER_CONTRACT_VERSION",
    "RUN_LEDGER_PATH_ENV",
    "Agent",
    "Approval",
    "AuditEvent",
    "Automation",
    "Capability",
    "CapabilityType",
    "Connection",
    "ConnectionKind",
    "ConsultantAccessGrant",
    "ConsultantGrantStatus",
    "ControlPlaneManifest",
    "ControlPlaneRunStatus",
    "ControlPlaneValidationError",
    "ExecutionMode",
    "ExecutionResult",
    "ImportRecord",
    "ImportSourceProtocol",
    "LifecycleState",
    "LocalApprovalNotification",
    "LocalApprovalNotificationChannel",
    "LocalApprovalNotificationEvent",
    "LocalApprovalNotificationStatus",
    "LocalObservabilityLogRecord",
    "Policy",
    "PolicyAttributeCondition",
    "PolicyAttributeExpression",
    "PolicyDecision",
    "PolicyDecisionReason",
    "PolicyDecisionRecord",
    "PolicyRulePack",
    "PolicyTemplate",
    "RunMode",
    "RunObservabilityMetrics",
    "RunRecord",
    "RunStepRecord",
    "RunStepStatus",
    "RunStepType",
    "SecretReference",
    "SecretMetadata",
    "SecretStorageScope",
    "SideEffect",
    "SyncConflictStrategy",
    "SyncDirection",
    "SyncRule",
    "TenantIsolationRule",
    "Trigger",
    "TriggerEventEnvelope",
    "TriggerIngestionResult",
    "TriggerKind",
    "WorkspaceRef",
    "RetrievalTrace",
    "RunLedgerEntry",
    "RunLedgerProvenance",
    "RunLedgerStatus",
    "Source",
    "SourceRef",
    "SourceType",
    "TERMINAL_RUN_STATUSES",
    "ValidationResult",
    "__version__",
    "build_memory_graph_fixture",
    "check_contract_version_compatibility",
    "normalize_graph_edge_id",
    "normalize_graph_node_id",
    "normalize_graph_node_kind",
    "normalize_graph_relation",
    "normalize_identifier",
    "normalize_label",
    "normalize_object_id",
    "normalize_object_kind",
    "normalize_source_path",
    "normalize_space_id",
    "normalize_tags",
    "detect_import_source_change",
    "ImportSourceChange",
    "import_asyncapi_candidates",
    "import_catalogue_candidates",
    "import_catalogue_generated_candidates",
    "import_mcp_candidates",
    "import_openapi_candidates",
    "validate_asyncapi_import_spec",
    "validate_mcp_import_spec",
    "validate_openapi_import_spec",
    "LocalModelInvocationRecord",
    "LocalUsageLedgerEntry",
    "compile_policy_expression",
    "manifest_from_dict",
    "summarize_confidence",
    "summarize_review_status",
    "summarize_sensitivity",
    "validate_agent_graph_context",
    "validate_agent_run_record",
    "validate_app_manifest",
    "validate_component_contract",
    "validate_control_plane_manifest",
    "verify_catalogue_artifacts",
    "validate_evidence_file_ref",
    "validate_graph_edge",
    "validate_graph_fragment",
    "validate_graph_node",
    "validate_module_manifest",
    "validate_knowledge_claim",
    "validate_knowledge_collection",
    "validate_knowledge_extension_manifest",
    "validate_knowledge_link",
    "validate_knowledge_object",
    "validate_knowledge_source",
    "validate_knowledge_space",
    "validate_run_ledger_entry",
    "SecretResolutionResult",
    "validate_run_ledger_provenance",
    "validate_source_ref",
]
