"""Stable contract-level OmniVia Core exports.

The package root is intentionally small. It exposes only portable knowledge
contracts, validators, and normalization helpers. Runtime scanners, caches,
providers, search services, persistence layers, MCP surfaces, and installers
remain outside the root public API.
"""

from omnivia_memory.knowledge import (
    BUILTIN_GRAPH_NODE_KINDS,
    BUILTIN_GRAPH_RELATIONS,
    BUILTIN_OBJECT_KINDS,
    EXTENSION_MANIFEST_CONTRACT_VERSION,
    GRAPH_CONTRACT_VERSION,
    KNOWLEDGE_CONTRACT_VERSION,
    AgentGraphContext,
    ContractVersion,
    GraphConfidence,
    GraphEdge,
    GraphEvidenceStrength,
    GraphFragment,
    GraphNode,
    GraphOrigin,
    GraphReviewStatus,
    GraphSensitivity,
    GraphSourceType,
    GraphVisibility,
    KnowledgeClaim,
    KnowledgeCollection,
    KnowledgeExtensionManifest,
    KnowledgeLink,
    KnowledgeObject,
    KnowledgeSource,
    KnowledgeSpace,
    SourceRef,
    ValidationResult,
    check_contract_version_compatibility,
    normalize_graph_edge_id,
    normalize_graph_node_id,
    normalize_graph_node_kind,
    normalize_graph_relation,
    normalize_identifier,
    normalize_label,
    normalize_object_id,
    normalize_object_kind,
    normalize_source_path,
    normalize_space_id,
    normalize_tags,
    summarize_confidence,
    summarize_review_status,
    summarize_sensitivity,
    validate_agent_graph_context,
    validate_graph_edge,
    validate_graph_fragment,
    validate_graph_node,
    validate_knowledge_claim,
    validate_knowledge_collection,
    validate_knowledge_extension_manifest,
    validate_knowledge_link,
    validate_knowledge_object,
    validate_knowledge_source,
    validate_knowledge_space,
    validate_source_ref,
)
from omnivia_memory.memory_graph import (
    EvidenceGraphResponse,
    GraphPreviewResponse,
    MemoryGraphFixture,
    RetrievalTrace,
    build_memory_graph_fixture,
)

# Compatibility re-exports for downstream consumers that import manifest
# contracts, provenance primitives, and the memory runtime surface from the
# package root. These are re-exported from their existing submodule paths only;
# no code is moved. The runtime-heavy symbols (Database, MemoryService, the
# MemoryCreate/MemoryUpdate inputs, and Source/SourceType) are intentionally
# kept out of __all__ so the root's advertised public API stays contract-only,
# while remaining importable for callers that request them explicitly.
from .app_manifest import (
    AppManifest,
    AppManifestValidationError,
    AppState,
    DataSource,
    validate_app_manifest,
)
from .component_contract import (
    AgentAction,
    AgentBackedComponentContract,
    AgentBehavior,
    AgentRunRecord,
    AgentRunStatus,
    ApprovalPolicy,
    AuditRequirement,
    ComponentAIMode,
    ComponentConnectorScope,
    ComponentContract,
    ComponentContractValidationError,
    ComponentDataSource,
    ComponentFamily,
    ComponentGraphScope,
    ComponentInput,
    ComponentOutput,
    ComponentOutputType,
    ComponentPermission,
    ComponentRunMode,
    ComponentSafetyLevel,
    PermissionPolicy,
    ProvenanceBehavior,
    ProvenanceRequirement,
    validate_agent_run_record,
    validate_component_contract,
)
from .memory import MemoryCreate, MemoryService, MemoryUpdate
from .module_manifest import (
    Entrypoint,
    Integrity,
    ModuleKind,
    ModuleManifest,
    ModuleManifestValidationError,
    Permission,
    PublishedTarget,
    validate_module_manifest,
)
from .persistence import Database
from .provenance import Source, SourceType
from .run_ledger import (
    RUN_LEDGER_CONTRACT_VERSION,
    RUN_LEDGER_PATH_ENV,
    TERMINAL_RUN_STATUSES,
    EvidenceFileRef,
    RunLedgerEntry,
    RunLedgerProvenance,
    RunLedgerStatus,
    validate_evidence_file_ref,
    validate_run_ledger_entry,
    validate_run_ledger_provenance,
)

__version__ = "0.1.0"

__all__ = [
    "AgentGraphContext",
    "AppManifest",
    "AppManifestValidationError",
    "AppState",
    "AgentAction",
    "AgentBackedComponentContract",
    "AgentBehavior",
    "AgentRunRecord",
    "AgentRunStatus",
    "ApprovalPolicy",
    "AuditRequirement",
    "BUILTIN_GRAPH_NODE_KINDS",
    "BUILTIN_GRAPH_RELATIONS",
    "BUILTIN_OBJECT_KINDS",
    "ComponentAIMode",
    "ComponentConnectorScope",
    "ComponentContract",
    "ComponentContractValidationError",
    "ComponentDataSource",
    "ComponentFamily",
    "ComponentGraphScope",
    "ComponentInput",
    "ComponentOutput",
    "ComponentOutputType",
    "ComponentPermission",
    "ComponentRunMode",
    "ComponentSafetyLevel",
    "ContractVersion",
    "DataSource",
    "Entrypoint",
    "EXTENSION_MANIFEST_CONTRACT_VERSION",
    "EvidenceFileRef",
    "EvidenceGraphResponse",
    "GRAPH_CONTRACT_VERSION",
    "GraphConfidence",
    "GraphPreviewResponse",
    "GraphEdge",
    "GraphEvidenceStrength",
    "GraphFragment",
    "GraphNode",
    "GraphOrigin",
    "GraphReviewStatus",
    "GraphSensitivity",
    "GraphSourceType",
    "GraphVisibility",
    "Integrity",
    "KNOWLEDGE_CONTRACT_VERSION",
    "KnowledgeClaim",
    "KnowledgeCollection",
    "KnowledgeExtensionManifest",
    "KnowledgeLink",
    "KnowledgeObject",
    "KnowledgeSource",
    "KnowledgeSpace",
    "MemoryGraphFixture",
    "ModuleKind",
    "ModuleManifest",
    "ModuleManifestValidationError",
    "Permission",
    "PermissionPolicy",
    "PublishedTarget",
    "ProvenanceBehavior",
    "ProvenanceRequirement",
    "RUN_LEDGER_CONTRACT_VERSION",
    "RUN_LEDGER_PATH_ENV",
    "RetrievalTrace",
    "RunLedgerEntry",
    "RunLedgerProvenance",
    "RunLedgerStatus",
    "Source",
    "SourceRef",
    "SourceType",
    "TERMINAL_RUN_STATUSES",
    "ValidationResult",
    "__version__",
    "build_memory_graph_fixture",
    "check_contract_version_compatibility",
    "normalize_graph_edge_id",
    "normalize_graph_node_id",
    "normalize_graph_node_kind",
    "normalize_graph_relation",
    "normalize_identifier",
    "normalize_label",
    "normalize_object_id",
    "normalize_object_kind",
    "normalize_source_path",
    "normalize_space_id",
    "normalize_tags",
    "summarize_confidence",
    "summarize_review_status",
    "summarize_sensitivity",
    "validate_agent_graph_context",
    "validate_agent_run_record",
    "validate_app_manifest",
    "validate_component_contract",
    "validate_evidence_file_ref",
    "validate_graph_edge",
    "validate_graph_fragment",
    "validate_graph_node",
    "validate_module_manifest",
    "validate_knowledge_claim",
    "validate_knowledge_collection",
    "validate_knowledge_extension_manifest",
    "validate_knowledge_link",
    "validate_knowledge_object",
    "validate_knowledge_source",
    "validate_knowledge_space",
    "validate_run_ledger_entry",
    "validate_run_ledger_provenance",
    "validate_source_ref",
]
