"""P2b sub-lane A: the HTTP v1 adapter as a TLS listener.

Hermetic. No hosted environment, no committed certificate, no network beyond this
host's own interfaces. What is pinned here is the capability sub-lane B will point a
real hostname at, and the four refusals that keep it from being a downgrade:

* a non-loopback bind serves **only** with TLS configured, and refuses at construction
  without it -- the merged refusal, unchanged;
* TLS material that cannot be loaded refuses **before a socket exists**, asserted on
  the port rather than on the exception;
* the protocol floor is TLS 1.2 and is stated rather than inherited;
* a cleartext caller is never answered as HTTP by a listener that was asked for TLS.

The last one is the one that has to be observed on the wire. A test that reads the
configuration back proves the configuration; only bytes prove what is served.

Certificate material is generated by the `openssl` CLI into pytest's own temporary
directory, once per session. Nothing is written into the work tree and no dependency
is added for it: if `openssl` is missing this module **fails**, loudly, rather than
skipping -- a skipped test reads exactly like a passing one in a summary line.
"""

from __future__ import annotations

import ipaddress
import json
import socket
import ssl
import subprocess
import time
import traceback
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pytest
from omnivia_core_runtime.service.authorization import AuthenticatedSession
from omnivia_core_runtime.service.http_transport import (
    APPLICATION_PATH,
    CONTENT_TYPE,
    PROBE_PATH,
    HttpBind,
    HttpListener,
    HttpTls,
    HttpTransportError,
    parse_http_endpoint,
)
from omnivia_core_runtime.service.operations import success
from omnivia_core_runtime.service.ovc1 import canonical_json_bytes
from omnivia_core_runtime.service.probes import PROBE_HEALTH, ProbeRouter, ServiceFacts
from omnivia_core_runtime.service.protocol import PROBE_FIELD, DocumentRouter
from omnivia_core_runtime.service.versions import API_VERSION

from omnivia_core.contracts.v1 import (
    ClientIdentity,
    RequestEnvelope,
    RequestMetadata,
    ResponseEnvelope,
)

OBSERVED_AT = "2026-08-05T00:00:00Z"
OPERATION = "core.health"
WORKSPACE = "ws-1"
PRINCIPAL = "local-user"
ACCEPTED_CREDENTIAL = "accepted-credential"

#: The planted values, spelled exactly as `test_http_security.py` spells them so the
#: cleartext and TLS redaction proofs are searching for the same two strings.
#: `PLANTED_CREDENTIAL` doubles as a certificate filename below -- `ssl` quotes the file
#: it could not read, and a path is a filesystem layout this process may not publish.
PLANTED_CREDENTIAL = "planted-credential-hunter2"
PLANTED_PATH = "/Users/alice/private/tokens.json"


# --- the router behind the listener -------------------------------------------


class CountingDispatch:
    def __init__(self) -> None:
        self.calls: list[RequestEnvelope] = []

    def __call__(self, request: RequestEnvelope) -> ResponseEnvelope:
        self.calls.append(request)
        return success(request, {"ok": True}, principal=PRINCIPAL)


def _facts() -> ServiceFacts:
    return ServiceFacts(
        observed_at=OBSERVED_AT,
        health_status="pass",
        readiness_status="pass",
        discovery_status="pass",
    )


def _router(dispatch: CountingDispatch) -> DocumentRouter:
    return DocumentRouter(
        probes=ProbeRouter(facts=_facts, capabilities=tuple, clock=lambda: 0),
        dispatch=dispatch,
    )


def _resolver(credential: str) -> AuthenticatedSession | None:
    if credential != ACCEPTED_CREDENTIAL:
        return None
    return AuthenticatedSession(
        principal_id=PRINCIPAL,
        roles=frozenset({"reader"}),
        workspaces=frozenset({WORKSPACE}),
        operations=frozenset({OPERATION}),
        purposes=frozenset({"test"}),
        scopes=frozenset({"workspace:read"}),
    )


def _request_bytes() -> bytes:
    envelope = RequestEnvelope(
        operation=OPERATION,
        metadata=RequestMetadata(
            request_id="req-1",
            correlation_id="corr-1",
            trace_id="trace-1",
            api_version=API_VERSION,
            client=ClientIdentity(id="test-client", version="0.1.0"),
            scopes=("workspace:read",),
            purpose="test",
            required_capabilities=(),
            workspace_id=WORKSPACE,
        ),
        input={},
    )
    return canonical_json_bytes(envelope.to_wire())


# --- certificate material, generated and never committed ----------------------


@dataclass(frozen=True)
class Material:
    """One locally generated chain, and the anchor a strict client trusts it by.

    `issuing_ca` is the anchor. It is deliberately *not* the leaf: a client that trusts
    the certificate it is testing against proves nothing, so the client context below
    is anchored on the issuer and verifies the chain and the name like any other.
    """

    issuing_ca: Path
    certificate_chain: Path
    private_key: Path
    #: A second, unrelated key -- the CA's -- so "the key does not match the chain" is a
    #: real mismatch rather than a corrupted file.
    unrelated_key: Path
    names: tuple[str, ...]

    @property
    def tls(self) -> HttpTls:
        return HttpTls(
            certificate_chain=self.certificate_chain, private_key=self.private_key
        )


def _openssl(*arguments: str) -> None:
    """Run `openssl`, and fail the run if it is not there.

    No `importorskip`, no `shutil.which` guard and no `skipif`. An environment without
    `openssl` cannot certify this capability, and a skip would report that as a pass.
    `FileNotFoundError` from a missing binary and `CalledProcessError` from a refused
    invocation both end the test with the reason attached.
    """
    subprocess.run(("openssl", *arguments), check=True, capture_output=True)


def _generate(root: Path, names: tuple[str, ...]) -> Material:
    """A one-day CA and one leaf it issues, into `root`.

    P-256 rather than RSA because this runs once per session and a keygen that costs
    milliseconds instead of hundreds of them is the difference between a fixture and a
    tax. `.pem` and `.key` are the two extensions `.gitignore` already covers -- and
    `root` is pytest's own temporary directory, so nothing lands in the work tree to
    need covering in the first place.
    """
    subject_alternative = ",".join(
        f"IP:{name}" if _is_ip(name) else f"DNS:{name}" for name in names
    )
    extensions = root / "leaf.ext"
    extensions.write_text(
        f"subjectAltName={subject_alternative}\n"
        "basicConstraints=critical,CA:FALSE\n"
        "keyUsage=critical,digitalSignature,keyEncipherment\n"
        "extendedKeyUsage=serverAuth\n",
        encoding="utf-8",
    )
    ca_key, ca_chain = root / "ca.key", root / "ca.pem"
    leaf_key, leaf_chain, request = root / "leaf.key", root / "leaf.pem", root / "l.csr"
    curve = ("-newkey", "ec", "-pkeyopt", "ec_paramgen_curve:P-256", "-nodes")
    _openssl(
        "req", "-x509", *curve,
        "-keyout", str(ca_key), "-out", str(ca_chain), "-days", "1",
        "-subj", "/CN=omnivia-core-tls-sublane-a-ca",
        "-addext", "basicConstraints=critical,CA:TRUE",
    )  # fmt: skip
    _openssl(
        "req", *curve,
        "-keyout", str(leaf_key), "-out", str(request), "-subj", f"/CN={names[0]}",
    )  # fmt: skip
    _openssl(
        "x509", "-req", "-in", str(request), "-CA", str(ca_chain),
        "-CAkey", str(ca_key), "-CAcreateserial", "-out", str(leaf_chain),
        "-days", "1", "-extfile", str(extensions),
    )  # fmt: skip
    return Material(
        issuing_ca=ca_chain,
        certificate_chain=leaf_chain,
        private_key=leaf_key,
        unrelated_key=ca_key,
        names=names,
    )


def _is_ip(name: str) -> bool:
    try:
        ipaddress.ip_address(name)
    except ValueError:
        return False
    return True


def _routable_address() -> str:
    """A non-loopback IPv4 address this host actually holds.

    Required rather than optional: the packet's evidence binds a routable address of
    the runner itself, and an environment that cannot produce one has not exercised the
    non-loopback path. So this raises rather than skipping or quietly falling back to
    `127.0.0.1`, which would turn the headline evidence into a second loopback test
    while the summary line stayed green.

    A datagram `connect` sends nothing. It only fixes the route, which is how the host
    is asked which source address it would speak from -- `gethostbyname` is the fallback
    because a machine with no default route can still know its own name.
    """
    candidates: list[str] = []
    probe = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        probe.connect(("192.0.2.1", 9))
        candidates.append(str(probe.getsockname()[0]))
    except OSError:
        pass
    finally:
        probe.close()
    try:
        candidates.append(socket.gethostbyname(socket.gethostname()))
    except OSError:
        pass
    for candidate in candidates:
        if _is_ip(candidate) and not ipaddress.ip_address(candidate).is_loopback:
            return candidate
    raise AssertionError(
        "this host holds no non-loopback IPv4 address, so the non-loopback TLS "
        "evidence cannot be produced here; record the environment rather than "
        "narrowing the test"
    )


@pytest.fixture(scope="session")
def routable() -> str:
    return _routable_address()


@pytest.fixture(scope="session")
def material(tmp_path_factory: pytest.TempPathFactory, routable: str) -> Material:
    """One chain per session, covering loopback and this runner's routable address."""
    return _generate(
        tmp_path_factory.mktemp("tls-material"),
        ("127.0.0.1", "::1", "localhost", routable),
    )


# --- the client, built once and never relaxed ---------------------------------


def _client(material: Material) -> ssl.SSLContext:
    """One strict context, anchored on the issuer and used for every case.

    `create_default_context` leaves `check_hostname` True and `verify_mode`
    `CERT_REQUIRED`, and nothing here lowers either. A negative case that builds a
    laxer client is the single most common way a TLS suite passes for the wrong reason,
    so there is one builder and it has no arguments to weaken.
    """
    return ssl.create_default_context(cafile=str(material.issuing_ca))


class Serving:
    def __init__(self, server: HttpListener, dispatch: CountingDispatch) -> None:
        self.server = server
        self.dispatch = dispatch
        self.url = server.url
        self.host = server.bind.host
        service = server._service
        assert service is not None
        self.service = service
        self.port = int(service.server_address[1])


def _serve(
    tls: HttpTls | None,
    *,
    host: str = "127.0.0.1",
    deadline: float = 10.0,
    resolver: Any = _resolver,
) -> Serving:
    dispatch = CountingDispatch()
    server = HttpListener(
        router=_router(dispatch),
        principal=PRINCIPAL,
        resolver=resolver,
        bind=HttpBind(host=host, tls=tls),
        request_deadline=deadline,
    )
    server.start()
    return Serving(server, dispatch)


@pytest.fixture
def serving(material: Material) -> Iterator[Serving]:
    live = _serve(material.tls)
    try:
        yield live
    finally:
        live.server.stop()


def _tls_exchange(
    context: ssl.SSLContext, host: str, port: int, head: list[str], body: bytes
) -> tuple[int, bytes, bytes, str]:
    """One request over TLS. Status, response head, body, and the negotiated version.

    The head is returned as well as the body, which the merged cleartext helper does
    not do. A refusal carries no body by construction, so a diagnostic header is the
    one place in a *response* a planted value could still survive -- and the redaction
    proof below asserts on both halves rather than on the half that is empty anyway.
    """
    raw = ("\r\n".join(head) + "\r\n\r\n").encode("latin-1") + body
    with (
        socket.create_connection((host, port), timeout=20) as plain,
        context.wrap_socket(plain, server_hostname=host) as client,
    ):
        negotiated = client.version() or ""
        client.sendall(raw)
        chunks: list[bytes] = []
        while True:
            chunk = client.recv(65536)
            if not chunk:
                break
            chunks.append(chunk)
    response = b"".join(chunks)
    head_bytes, _, response_body = response.partition(b"\r\n\r\n")
    status = int(head_bytes.split(b"\r\n", 1)[0].split(b" ")[1])
    return status, head_bytes, response_body, negotiated


def _tls_post(
    context: ssl.SSLContext,
    host: str,
    port: int,
    path: str,
    body: bytes,
    *,
    credential: str | None = None,
) -> tuple[int, bytes, bytes, str]:
    head = [
        f"POST {path} HTTP/1.1",
        f"Host: {host}",
        f"Content-Type: {CONTENT_TYPE}",
        f"Content-Length: {len(body)}",
    ]
    if credential is not None:
        head.insert(2, f"Authorization: Bearer {credential}")
    return _tls_exchange(context, host, port, head, body)


def _reserved_port() -> int:
    """A port nothing is listening on, so "bound no socket" can be asserted on it."""
    with socket.socket() as probe:
        probe.bind(("127.0.0.1", 0))
        return int(probe.getsockname()[1])


def _nothing_is_listening(host: str, port: int) -> bool:
    try:
        with socket.create_connection((host, port), timeout=2):
            return False
    except OSError:
        return True


# --- the capability -----------------------------------------------------------


def test_a_tls_listener_answers_a_strict_client_anchored_on_the_issuing_ca(
    serving: Serving, material: Material
) -> None:
    """The positive case, and the counterweight to every refusal below.

    Four refusals and no success proves only that the client is broken, so this runs
    the same strict context every negative case runs and gets an accepted envelope
    back through it.
    """
    status, _, body, negotiated = _tls_post(
        _client(material),
        serving.host,
        serving.port,
        APPLICATION_PATH,
        _request_bytes(),
        credential=ACCEPTED_CREDENTIAL,
    )

    assert status == 200
    document = json.loads(body)
    assert document["result"] == {"ok": True}
    assert [seen.operation for seen in serving.dispatch.calls] == [OPERATION]
    # A floor, not a ceiling: 1.2 is the minimum and 1.3 is what two modern peers pick.
    assert negotiated in ("TLSv1.2", "TLSv1.3")


def test_a_non_loopback_bind_with_tls_starts_and_serves_that_same_client(
    material: Material, routable: str
) -> None:
    """The whole point of the lane: a routable address, terminated by Core itself.

    Bound to an address of this runner, not a hostname -- a server binds an address and
    the name is the certificate's subject and the peer's concern. The chain is verified
    against the address connected to, by the same anchored client, so what this
    certifies is the chain Core presents rather than a socket that happened to open.
    """
    live = _serve(material.tls, host=routable)
    try:
        assert live.url.startswith(f"https://{routable}:")
        status, _, body, _ = _tls_post(
            _client(material),
            routable,
            live.port,
            APPLICATION_PATH,
            _request_bytes(),
            credential=ACCEPTED_CREDENTIAL,
        )
    finally:
        live.server.stop()

    assert status == 200
    assert json.loads(body)["result"] == {"ok": True}
    assert len(live.dispatch.calls) == 1


def test_an_unauthenticated_request_over_tls_still_never_reaches_dispatch(
    serving: Serving, material: Material
) -> None:
    """The merged trust boundary, re-proved over the new transport rather than assumed.

    TLS is a transport, so it must not have moved the credential check. Asserted on the
    dispatcher, as the merged loopback suite does, not on the number 401.
    """
    status, _, body, _ = _tls_post(
        _client(material),
        serving.host,
        serving.port,
        APPLICATION_PATH,
        _request_bytes(),
    )

    assert status == 401
    assert body == b""
    assert serving.dispatch.calls == []


# --- and never in the clear ---------------------------------------------------


def test_a_cleartext_request_to_a_tls_port_is_not_answered_as_http(
    serving: Serving,
) -> None:
    """Constraint: no downgrade, observed on the wire rather than in the configuration.

    A plain HTTP request -- a well-formed probe, which this adapter answers
    unauthenticated over cleartext loopback -- is sent to the TLS port as bytes. What
    must come back is *not an HTTP response*: no status line, no headers, no envelope,
    no upgrade offer. OpenSSL reads `POST /v1/probe` as a TLS record it cannot parse,
    the handshake never completes, and `get_request` closes the connection without ever
    constructing a handler, which is why the router is untouched as well.

    This is the assertion a config-reading test cannot make. A listener that skipped
    the wrap would answer this exchange with `HTTP/1.0 200` and every other test in
    this module could still pass.
    """
    body = canonical_json_bytes({PROBE_FIELD: PROBE_HEALTH})
    request = (
        f"POST {PROBE_PATH} HTTP/1.1\r\n"
        f"Host: {serving.host}\r\n"
        f"Content-Type: {CONTENT_TYPE}\r\n"
        f"Content-Length: {len(body)}\r\n\r\n"
    ).encode("latin-1") + body

    chunks: list[bytes] = []
    with socket.create_connection((serving.host, serving.port), timeout=20) as client:
        client.sendall(request)
        try:
            while True:
                chunk = client.recv(65536)
                if not chunk:
                    break
                chunks.append(chunk)
        except OSError:
            # A reset is one of the acceptable answers; being *answered* is not.
            pass
    answer = b"".join(chunks)

    assert b"HTTP/" not in answer
    assert b"200" not in answer
    assert PROBE_HEALTH.encode() not in answer
    assert serving.dispatch.calls == []
    # Still serving: the refusal cost this listener one connection, not its life.
    assert _nothing_is_listening(serving.host, serving.port) is False


def test_a_listener_asked_for_tls_with_no_context_refuses_rather_than_downgrading(
    serving: Serving, material: Material
) -> None:
    """The one state between "TLS was asked for" and "TLS is loaded", pinned closed.

    `start` builds the context before it binds, so this state is unreachable from any
    caller -- which is exactly why it is worth pinning: an unreachable branch nothing
    asserts on is a branch a later refactor deletes, and deleting *this* one turns
    `get_request`'s TLS arm into a fall-through to the cleartext return above it.

    Reached by clearing the loaded context on a live listener, which is the smallest
    possible statement of "the material went away". The bind still says TLS, so the
    only permitted outcome is a closed connection.
    """
    serving.service.tls = None
    with pytest.raises((ssl.SSLError, ConnectionResetError)):
        _tls_post(
            _client(material),
            serving.host,
            serving.port,
            PROBE_PATH,
            canonical_json_bytes({PROBE_FIELD: PROBE_HEALTH}),
        )

    # And not in the clear either: the cleartext caller is dropped, not served.
    with socket.create_connection((serving.host, serving.port), timeout=20) as client:
        client.sendall(
            b"POST /v1/probe HTTP/1.1\r\nHost: x\r\nContent-Length: 0\r\n\r\n"
        )
        try:
            answer = client.recv(65536)
        except OSError:
            answer = b""
    assert answer == b""
    assert serving.dispatch.calls == []


def test_the_url_reports_the_scheme_it_is_actually_serving(material: Material) -> None:
    """`url` is what a caller connects to, so a hardcoded scheme is a downgrade invite."""
    secure = _serve(material.tls)
    try:
        assert secure.url.startswith("https://127.0.0.1:")
    finally:
        secure.server.stop()

    cleartext = _serve(None)
    try:
        assert cleartext.url.startswith("http://127.0.0.1:")
    finally:
        cleartext.server.stop()


# --- and never without a full, usable configuration ---------------------------


@pytest.mark.parametrize("host", ["192.0.2.1", "2001:db8::1", "0.0.0.0", "::"])
def test_a_non_loopback_bind_without_tls_still_refuses_at_construction(
    host: str,
) -> None:
    """The merged refusal, unchanged, and still before anything can listen.

    TLS on the bind is the *whole* of what opens this. Without it the wildcard and
    routable cases refuse exactly where they always did, so there is no state in which
    a routable listener is up in the clear -- there is no object to have started.
    """
    with pytest.raises(HttpTransportError, match="loopback"):
        HttpBind(host=host)


def test_a_non_loopback_bind_without_tls_leaves_nothing_listening(
    routable: str,
) -> None:
    """Asserted on the port, not only on the exception.

    A refusal that raised after binding would satisfy `pytest.raises` and still have
    opened the socket the refusal exists to prevent.
    """
    port = _reserved_port()

    with pytest.raises(HttpTransportError):
        HttpListener(
            router=_router(CountingDispatch()),
            principal=PRINCIPAL,
            resolver=_resolver,
            bind=HttpBind(host=routable, port=port),
        )

    assert _nothing_is_listening(routable, port)


@pytest.mark.parametrize(
    "case",
    ["absent_chain", "absent_key", "chain_is_a_directory", "key_does_not_match_chain"],
)
def test_tls_material_that_cannot_be_loaded_refuses_startup_and_binds_no_socket(
    material: Material, tmp_path: Path, case: str
) -> None:
    """Fail closed, before the socket, and asserted on the port.

    "Raised an exception" is not the claim. The claim is that no listener exists
    afterwards -- a context built after binding would leave a live port answering
    nothing, which is worse than a refusal and looks identical in a `pytest.raises`.
    """
    absent = tmp_path / "not-here.pem"
    tls = {
        "absent_chain": HttpTls(absent, material.private_key),
        "absent_key": HttpTls(material.certificate_chain, absent),
        "chain_is_a_directory": HttpTls(tmp_path, material.private_key),
        "key_does_not_match_chain": HttpTls(
            material.certificate_chain, material.unrelated_key
        ),
    }[case]
    port = _reserved_port()
    server = HttpListener(
        router=_router(CountingDispatch()),
        principal=PRINCIPAL,
        resolver=_resolver,
        bind=HttpBind(port=port, tls=tls),
    )

    with pytest.raises(HttpTransportError, match="TLS material"):
        server.start()

    assert _nothing_is_listening("127.0.0.1", port)
    assert server._service is None


def test_the_protocol_floor_is_stated_at_tls_1_2_and_holds_against_a_1_1_client(
    serving: Serving, material: Material
) -> None:
    """The floor, twice: as configured and as enforced on the wire.

    The configured half is exact -- `minimum_version` is read off the context the live
    listener is actually using, so inheriting whatever the platform default is this
    year fails here rather than passing quietly.

    The enforced half is attributable rather than "something raised": the client is
    capped at TLS 1.1 and the refusal is asserted through `SSLError.reason`, which
    names a protocol-version condition and never a certificate one. `@SECLEVEL=0` is
    needed to make the client willing to *send* a 1.1 hello at all on OpenSSL 3 -- with
    the default security level the client refuses first and the server's floor is never
    reached, which would be a test that passes without exercising the thing it names.
    """
    assert serving.service.tls is not None
    assert serving.service.tls.minimum_version is ssl.TLSVersion.TLSv1_2

    old = _client(material)
    old.set_ciphers("DEFAULT@SECLEVEL=0")
    old.minimum_version = ssl.TLSVersion.TLSv1_1
    old.maximum_version = ssl.TLSVersion.TLSv1_1

    with pytest.raises(ssl.SSLError) as caught:
        _tls_post(
            old,
            serving.host,
            serving.port,
            PROBE_PATH,
            canonical_json_bytes({PROBE_FIELD: PROBE_HEALTH}),
        )

    assert caught.value.reason in (
        "TLSV1_ALERT_PROTOCOL_VERSION",
        "UNSUPPORTED_PROTOCOL",
        "VERSION_TOO_LOW",
    )
    assert serving.dispatch.calls == []


def test_client_certificates_are_out_of_scope_and_the_context_says_so(
    serving: Serving,
) -> None:
    """A recorded boundary rather than an oversight.

    Mutual TLS is not in this lane. `PROTOCOL_TLS_SERVER` asks for no client
    certificate, and asking for one that nothing verifies would be ceremony -- so the
    absence is pinned, and turning it on becomes a visible decision rather than a
    silent one.
    """
    assert serving.service.tls is not None
    assert serving.service.tls.verify_mode is ssl.CERT_NONE


# --- and never for longer than the caller is owed -----------------------------


def test_a_peer_that_never_finishes_the_handshake_does_not_hold_the_listener(
    material: Material,
) -> None:
    """The handshake happens before there is a request, so the request budget is not it.

    A serialized listener means one silent peer is every other caller's wait. Measured
    the way the merged drip test measures: with the silent peer *still connected*, a
    real client is served, and the time it took is the bound.
    """
    live = _serve(material.tls, deadline=1.0)
    try:
        silent = socket.create_connection((live.host, live.port), timeout=20)
        try:
            started = time.monotonic()
            status, _, _, _ = _tls_post(
                _client(material),
                live.host,
                live.port,
                PROBE_PATH,
                canonical_json_bytes({PROBE_FIELD: PROBE_HEALTH}),
            )
            served_after = time.monotonic() - started
        finally:
            silent.close()
    finally:
        live.server.stop()

    assert status == 200
    assert served_after < 5.0, (
        f"a peer that never spoke held the serialized listener for {served_after:.1f}s"
    )


def test_the_request_deadline_still_releases_a_tls_drip_and_frees_the_listener(
    material: Material,
) -> None:
    """`_expire` still bounds the caller over TLS, and it does *more* than in the clear.

    Measured rather than assumed, because `shutdown(SHUT_RD)` does not mean the same
    thing here. `ssl.SSLSocket.shutdown` sets `self._sslobj = None` before delegating,
    so it is not a half-close at all: it ends the TLS session in both directions. The
    cleartext path's remaining reads return EOF and the unfinished request comes back
    `411`; the TLS path's next read finds no SSL object, the handler unwinds into the
    silenced `handle_error`, and the caller gets a close with nothing in it.

    That is stricter containment, not weaker, and it is not the unbounded-wait class
    the OVC1 lane fixed -- which is why this asserts what the merged cleartext drip test
    asserts and nothing narrower. A status code was never the contract for a request
    that never finished arriving; being *let go of*, on time, with the serialized
    listener free for the next caller while the drip is still connected, is.
    """
    live = _serve(material.tls, deadline=1.0)
    started = time.monotonic()
    try:
        with socket.create_connection((live.host, live.port), timeout=20) as plain:
            context = _client(material)
            with context.wrap_socket(plain, server_hostname=live.host) as client:
                # A complete request line, then a header line that never ends.
                client.sendall(b"POST /v1/probe HTTP/1.1\r\nX-Drip: ")
                client.settimeout(10.0)
                chunks: list[bytes] = []
                try:
                    while True:
                        chunk = client.recv(65536)
                        if not chunk:
                            break
                        chunks.append(chunk)
                except OSError:
                    pass
                elapsed = time.monotonic() - started

                # The listener has to be free *while the drip is still connected*,
                # which is the property that matters on a serialized server and the
                # one closing the drip socket first would hide.
                next_started = time.monotonic()
                status, _, _, _ = _tls_post(
                    _client(material),
                    live.host,
                    live.port,
                    PROBE_PATH,
                    canonical_json_bytes({PROBE_FIELD: PROBE_HEALTH}),
                )
                served_after = time.monotonic() - next_started
    finally:
        live.server.stop()

    answer = b"".join(chunks)
    assert elapsed < 5.0, f"the TLS drip held the connection for {elapsed:.1f}s"
    assert status == 200
    assert served_after < 3.0, (
        f"the TLS drip held the serialized listener for a further {served_after:.1f}s"
    )
    # Whatever it was told, it was not served: no accepted answer reached it.
    assert b"200" not in answer
    assert PROBE_HEALTH.encode() not in answer
    assert live.dispatch.calls == []


# --- and never publishing what it read ----------------------------------------
#
# Packet 5.5 item 9 asks for the merged redaction proof re-run *over TLS*. It lives
# here rather than in `test_http_security.py` because the machinery each side needs
# points that way: the redaction assertions are a dozen lines of string search, while
# reaching them over TLS needs the session-scoped issuing CA, the strict client and
# `_serve` -- all of which already exist in this module. Copying a certificate
# authority into the security suite to reuse `_assert_hides` is the larger duplication,
# and importing across two test modules that are collected under bare basenames rather
# than as a package is exactly the fragility `tests/test_core_acceptance_workflow.py`
# already guards against. So: the plants are spelled identically to the merged suite's,
# and the surfaces asserted are the same ones -- response, output, `args`, `__cause__`,
# `__context__`, formatted traceback -- with the response *head* added, which the
# cleartext helpers discard.


def test_a_rejected_credential_over_tls_reaches_no_response_and_no_output(
    material: Material, capfd: pytest.CaptureFixture[str]
) -> None:
    """The merged planted-credential proof, re-run over the TLS transport.

    The hole this closes is specific. The merged suite never crosses TLS code, so a
    diagnostic added to the accept, handshake or error path would leak a bearer from a
    routable listener with the cleartext redaction suite entirely green. Two of those
    paths are reachable *only* over TLS: `_expire` unwinds a TLS handler into
    `handle_error` rather than answering `411`, and `get_request` is the only place a
    connection is touched before a handler exists.

    Every exchange below carries the planted credential in an `Authorization` header
    and the planted path in the URL, and the resolver raises quoting both -- the worst
    case, because a raising resolver is the one thing holding the credential in an
    exception's message while the adapter decides what to do with it.

    The response *head* is asserted as well as the body. A refusal carries no body by
    construction, so the body assertion is nearly free; a diagnostic header is where a
    planted value would actually survive, and neither merged helper returns one.
    """
    live = _serve(
        material.tls,
        resolver=lambda credential: (_ for _ in ()).throw(
            RuntimeError(f"resolver read {PLANTED_PATH} for {credential}")
        ),
        deadline=1.0,
    )
    seen: list[bytes] = []
    try:
        context = _client(material)
        for path in (
            APPLICATION_PATH,
            f"/v1/{PLANTED_CREDENTIAL}",
            f"{PROBE_PATH}?token={PLANTED_CREDENTIAL}",
        ):
            status, head, body, _ = _tls_post(
                context,
                live.host,
                live.port,
                path,
                _request_bytes(),
                credential=PLANTED_CREDENTIAL,
            )
            assert status in (401, 404)
            seen.extend((head, body))

        # An invented verb reaches `BaseHTTPRequestHandler`'s own error path, which by
        # default renders the method into an HTML body -- over TLS this time.
        _, head, body, _ = _tls_exchange(
            context,
            live.host,
            live.port,
            [
                f"{PLANTED_CREDENTIAL.upper().replace('-', '')} {PROBE_PATH} HTTP/1.1",
                f"Host: {live.host}",
                f"Authorization: Bearer {PLANTED_CREDENTIAL}",
            ],
            b"",
        )
        seen.extend((head, body))

        # The TLS-only route into `handle_error`: a handler that has already parsed the
        # `Authorization` header, cut off by the deadline. Over cleartext this answers
        # `411` and never reaches `handle_error` at all, so nothing merged covers it.
        with (
            socket.create_connection((live.host, live.port), timeout=20) as plain,
            context.wrap_socket(plain, server_hostname=live.host) as client,
        ):
            client.sendall(
                f"POST {APPLICATION_PATH} HTTP/1.1\r\n"
                f"Authorization: Bearer {PLANTED_CREDENTIAL}\r\n"
                "X-Drip: ".encode("latin-1")
            )
            client.settimeout(10.0)
            try:
                while chunk := client.recv(65536):
                    seen.append(chunk)
            except OSError:
                pass
    finally:
        live.server.stop()

    captured = capfd.readouterr()
    for secret in (PLANTED_CREDENTIAL, PLANTED_PATH, PLANTED_CREDENTIAL.upper()):
        assert all(secret.encode() not in part for part in seen), secret
        assert secret not in captured.out
        assert secret not in captured.err
    assert live.dispatch.calls == []


def test_an_accepted_credential_over_tls_publishes_nothing_either(
    material: Material, capfd: pytest.CaptureFixture[str]
) -> None:
    """The other direction: a verified credential is still a credential.

    Four lines' worth of coverage for the half of the surface a "rejected credential"
    test cannot see -- the accepted path runs further, through the claims gate and into
    dispatch, and `AuthenticatedSession` carries no field for the credential precisely
    so it stops at the adapter.
    """
    live = _serve(
        material.tls,
        resolver=lambda credential: (
            _resolver(ACCEPTED_CREDENTIAL) if credential == PLANTED_CREDENTIAL else None
        ),
    )
    try:
        status, head, body, _ = _tls_post(
            _client(material),
            live.host,
            live.port,
            APPLICATION_PATH,
            _request_bytes(),
            credential=PLANTED_CREDENTIAL,
        )
    finally:
        live.server.stop()

    captured = capfd.readouterr()
    assert status == 200
    assert PLANTED_CREDENTIAL.encode() not in head + body
    assert PLANTED_CREDENTIAL not in captured.out + captured.err
    # Nothing carried it into the request the dispatcher was handed either.
    assert PLANTED_CREDENTIAL not in repr(live.dispatch.calls[0])


def test_an_https_endpoint_refusal_hides_a_credential_carried_in_the_url(
    material: Material,
) -> None:
    """The exception surfaces, on the parse path this lane newly opened.

    `https://` used to be refused at the scheme check, one line before the `userinfo`
    check could ever run. It now parses past that, so a credential in an `https` URL
    reaches the credential refusal for the first time -- a new surface, and the one
    place on the TLS path where an exception a *caller holds* can have seen a bearer.

    Both refusal orders are asserted: with material stated the endpoint reaches the
    `userinfo` rule, and without it the scheme/material rule fires first. Neither may
    quote what it was handed, through `args`, `__cause__`, `__context__` or a rendered
    traceback -- `raise ... from None` clears the first and leaves the second.
    """
    endpoint = f"https://alice:{PLANTED_CREDENTIAL}@127.0.0.1:8080"

    for stated in (material.tls, None):
        with pytest.raises(HttpTransportError) as caught:
            parse_http_endpoint(endpoint, tls=stated)

        error = caught.value
        rendered = "".join(
            (
                str(error),
                repr(error.args),
                repr(error.__cause__),
                repr(error.__context__),
                "".join(traceback.format_exception(error)),
            )
        )
        assert PLANTED_CREDENTIAL not in rendered
        assert "alice" not in rendered
        assert error.__cause__ is None
        assert error.__context__ is None


def test_a_tls_material_refusal_publishes_no_certificate_path(tmp_path: Path) -> None:
    """`ssl` quotes the file it could not read, and this module must not repeat it.

    A new leak surface this lane introduces: `FileNotFoundError` names the path, and an
    `SSLError` from a mismatched key names it too. `from None` would not be enough --
    it clears `__cause__` and leaves `__context__` referencing the original, one
    attribute access from anything that logs the refusal.
    """
    planted = tmp_path / f"{PLANTED_CREDENTIAL}.pem"
    server = HttpListener(
        router=_router(CountingDispatch()),
        principal=PRINCIPAL,
        resolver=_resolver,
        bind=HttpBind(tls=HttpTls(planted, planted)),
    )

    with pytest.raises(HttpTransportError) as caught:
        server.start()

    error = caught.value
    rendered = "".join(
        (
            str(error),
            repr(error.args),
            repr(error.__cause__),
            repr(error.__context__),
            "".join(traceback.format_exception(error)),
        )
    )
    assert PLANTED_CREDENTIAL not in rendered
    assert str(tmp_path) not in rendered
    assert error.__cause__ is None
    assert error.__context__ is None


def test_a_failed_handshake_prints_nothing_and_does_not_stop_the_listener(
    serving: Serving, material: Material, capfd: pytest.CaptureFixture[str]
) -> None:
    """The handshake path is new output surface, and it stays silent.

    `socketserver` prints a traceback from `handle_error` by default, and a handshake
    failure carries the peer's own bytes. Captured at the file-descriptor level because
    the listener answers on its own thread, where `capsys` would see nothing.
    """
    with socket.create_connection((serving.host, serving.port), timeout=20) as client:
        client.sendall(b"not a tls record at all: " + PLANTED_CREDENTIAL.encode())
        try:
            client.recv(65536)
        except OSError:
            pass

    # Still serving, and the successful caller proves the listener survived.
    status, _, _, _ = _tls_post(
        _client(material),
        serving.host,
        serving.port,
        PROBE_PATH,
        canonical_json_bytes({PROBE_FIELD: PROBE_HEALTH}),
    )
    captured = capfd.readouterr()

    assert status == 200
    assert captured.out == ""
    assert captured.err == ""
    assert PLANTED_CREDENTIAL not in captured.out + captured.err


def test_nothing_this_module_generates_lands_in_the_work_tree(
    material: Material,
) -> None:
    """The stop condition, asserted rather than trusted.

    `.gitignore` covers `*.pem` and `*.key` but not `*.crt`, `*.p12` or `*.pfx`, so a
    stray write with one of those extensions would be committed silently. The rule this
    module follows is stronger than the ignore list: everything goes to pytest's own
    temporary directory and nothing is written under the checkout at all.
    """
    checkout = Path(__file__).resolve().parents[5]
    for path in (
        material.issuing_ca,
        material.certificate_chain,
        material.private_key,
        material.unrelated_key,
    ):
        assert path.is_file()
        assert checkout not in path.resolve().parents
